import reflex as rx
from aventura_rd_frontend.components.navbar import navbar
from aventura_rd_frontend.components.footer import footer
from aventura_rd_frontend.state.ofertas_state import OfertasState, Oferta

def hero_section() -> rx.Component:
    return rx.box(
        rx.box(
            rx.vstack(
                rx.text(
                    "ECOTURISMO · AVENTURA · NATURALEZA",
                    color="#9FCC6B",
                    font_size="13px",
                    letter_spacing="3px",
                    font_weight="500",
                ),
                rx.heading(
                    "La naturaleza te llama.",
                    size="9",
                    color="white",
                    text_align="center",
                    line_height="1.1",
                ),
                rx.heading(
                    "Nosotros te llevamos.",
                    size="9",
                    color="#9FCC6B",
                    text_align="center",
                    line_height="1.1",
                ),
                rx.text(
                    "Descubre las aventuras más emocionantes de República Dominicana. "
                    "Senderismo, rafting, zipline y mucho más.",
                    color="rgba(255,255,255,0.85)",
                    font_size="18px",
                    text_align="center",
                    max_width="600px",
                ),
                rx.hstack(
                    rx.link(
                        rx.button(
                            "Ver aventuras",
                            background="#BA7517",
                            color="white",
                            border_radius="8px",
                            padding="14px 32px",
                            font_size="16px",
                            font_weight="600",
                            cursor="pointer",
                            _hover={"background": "#9A6010", "transform": "translateY(-2px)"},
                        ),
                        href="#ofertas",
                    ),
                    rx.link(
                        rx.button(
                            "Contactarnos",
                            background="transparent",
                            color="white",
                            border="2px solid white",
                            border_radius="8px",
                            padding="14px 32px",
                            font_size="16px",
                            font_weight="600",
                            cursor="pointer",
                            _hover={"background": "rgba(255,255,255,0.1)"},
                        ),
                        href="#contacto",
                    ),
                    spacing="4",
                ),
                spacing="5",
                align="center",
                max_width="800px",
                margin="0 auto",
            ),
            background="rgba(0,0,0,0.55)",
            width="100%",
            height="100%",
            display="flex",
            align_items="center",
            justify_content="center",
            padding="80px 40px",
        ),
        background_image="url('https://images.unsplash.com/photo-1551632811-561732d1e306?w=1600')",
        background_size="cover",
        background_position="center",
        width="100%",
        min_height="90vh",
    )

def search_section() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.heading(
                "¿Qué aventura buscas?",
                size="6",
                color="#27500A",
                text_align="center",
            ),
            rx.hstack(
                rx.input(
    placeholder="🔍  Busca por destino o actividad...",
    value=OfertasState.busqueda,
    on_change=OfertasState.set_busqueda,
    border="2px solid #639922",
    border_radius="8px",
    padding="12px 16px",
    font_size="15px",
    width=["100%", "100%", "400px"],
    _focus={"border_color": "#27500A", "outline": "none"},
),
rx.button(
    "Buscar",
    on_click=OfertasState.buscar_ofertas,
    background="#27500A",
    color="white",
    border_radius="8px",
    padding="12px 28px",
    font_size="15px",
    font_weight="600",
    _hover={"background": "#639922"},
),
                spacing="3",
                flex_wrap="wrap",
                justify="center",
            ),
            spacing="4",
            align="center",
        ),
        background="white",
        padding="40px",
        box_shadow="0 4px 20px rgba(0,0,0,0.1)",
        border_radius="16px",
        max_width="800px",
        margin="-60px auto 0",
        position="relative",
        z_index="10",
        width="90%",
    )

def categoria_chip(categoria) -> rx.Component:
    return rx.button(
        categoria.nombre,
        on_click=OfertasState.filtrar_categoria(categoria.id),
        background=rx.cond(
            OfertasState.categoria_seleccionada == categoria.id,
            "#27500A",
            "white"
        ),
        color=rx.cond(
            OfertasState.categoria_seleccionada == categoria.id,
            "white",
            "#27500A"
        ),
        border="1.5px solid #27500A",
        border_radius="20px",
        padding="8px 18px",
        font_size="13px",
        font_weight="500",
        cursor="pointer",
        _hover={"background": "#639922", "color": "white", "border_color": "#639922"},
    )

def oferta_card(oferta: Oferta) -> rx.Component:
    return rx.box(
        rx.link(
            rx.vstack(
                rx.box(
                   rx.image(
    src=oferta.imagen_url,
    width="100%",
    height="200px",
    object_fit="cover",
    style={"display": "block", "min_width": "100%", "min_height": "200px"},
),
                    rx.box(
                        rx.text(
                            oferta.categoria["nombre"],
                            color="white",
                            font_size="11px",
                            font_weight="600",
                            letter_spacing="1px",
                        ),
                        background="#27500A",
                        padding="4px 10px",
                        border_radius="4px",
                        position="absolute",
                        top="12px",
                        left="12px",
                    ),
                    rx.box(
                        rx.text(
                            f"RD$ ",
                            color="#FAC775",
                            font_size="13px",
                            font_weight="700",
                            display="inline",
                        ),
                        rx.text(
                            oferta.precio.to_string(),
                            color="#FAC775",
                            font_size="13px",
                            font_weight="700",
                            display="inline",
                        ),
                        background="rgba(0,0,0,0.55)",
                        padding="4px 10px",
                        border_radius="4px",
                        position="absolute",
                        bottom="12px",
                        right="12px",
                    ),
                    position="relative",
                    overflow="hidden",
                    border_radius="12px 12px 0 0",
                ),
                rx.vstack(
                    rx.heading(
                        oferta.titulo,
                        size="4",
                        color="#27500A",
                        font_weight="600",
                    ),
                    rx.hstack(
                        rx.icon("map-pin", size=14, color="#639922"),
                        rx.text(oferta.destino, font_size="13px", color="#666"),
                        spacing="1",
                        align="center",
                    ),
                    rx.hstack(
                        rx.icon("clock", size=14, color="#639922"),
                        rx.text(
                            f"{oferta.duracion_dias} día(s)",
                            font_size="13px",
                            color="#666"
                        ),
                        rx.spacer(),
                        rx.icon("users", size=14, color="#639922"),
                        rx.text(
                            f"{oferta.cupos_disponibles} cupos",
                            font_size="13px",
                            color="#666"
                        ),
                        spacing="1",
                        align="center",
                        width="100%",
                    ),
                    rx.divider(border_color="#E8F5E0"),
                    rx.hstack(
                        rx.spacer(),
                        rx.button(
                            "Ver detalles →",
                            background="#27500A",
                            color="white",
                            border_radius="8px",
                            padding="8px 16px",
                            font_size="13px",
                            _hover={"background": "#639922"},
                        ),
                        align="center",
                        width="100%",
                    ),
                    spacing="3",
                    padding="16px",
                    align="start",
                    width="100%",
                ),
                spacing="0",
                width="100%",
            ),
            href=f"/descripcion/{oferta.id}",
            text_decoration="none",
        ),
        background="white",
        border_radius="12px",
        box_shadow="0 2px 12px rgba(0,0,0,0.08)",
        overflow="hidden",
        transition="transform 0.2s, box-shadow 0.2s",
        _hover={
            "transform": "translateY(-4px)",
            "box_shadow": "0 8px 24px rgba(0,0,0,0.15)"
        },
        width="100%",
    )

def ofertas_section() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.vstack(
                rx.text(
                    "NUESTRAS AVENTURAS",
                    color="#639922",
                    font_size="12px",
                    letter_spacing="3px",
                    font_weight="600",
                ),
                rx.heading(
                    "Elige tu próxima aventura",
                    size="7",
                    color="#27500A",
                    text_align="center",
                ),
                rx.text(
                    "Desde el Pico Duarte hasta los ríos de Jarabacoa, "
                    "tenemos la experiencia perfecta para ti.",
                    color="#666",
                    text_align="center",
                    max_width="500px",
                ),
                spacing="2",
                align="center",
            ),
            rx.hstack(
                rx.button(
                    "Todas",
                    on_click=OfertasState.filtrar_categoria(0),
                    background=rx.cond(
                        OfertasState.categoria_seleccionada == 0,
                        "#27500A",
                        "white"
                    ),
                    color=rx.cond(
                        OfertasState.categoria_seleccionada == 0,
                        "white",
                        "#27500A"
                    ),
                    border="1.5px solid #27500A",
                    border_radius="20px",
                    padding="8px 18px",
                    font_size="13px",
                    font_weight="500",
                    cursor="pointer",
                    _hover={"background": "#639922", "color": "white"},
                ),
                rx.foreach(
                    OfertasState.categorias,
                    categoria_chip,
                ),
                flex_wrap="wrap",
                spacing="2",
                justify="center",
            ),
            rx.cond(
                OfertasState.cargando,
                rx.vstack(
                    rx.spinner(size="3", color="#27500A"),
                    rx.text("Cargando aventuras...", color="#666"),
                    spacing="3",
                    align="center",
                    padding="60px",
                ),
                rx.cond(
                    OfertasState.error != "",
                    rx.text(OfertasState.error, color="red", text_align="center"),
                    rx.grid(
                        rx.foreach(OfertasState.ofertas, oferta_card),
                        columns=rx.breakpoints({"base": "1", "md": "2", "lg": "3"}),
                        spacing="5",
                        width="100%",
                    ),
                ),
            ),
            spacing="8",
            align="center",
            width="100%",
            max_width="1200px",
            margin="0 auto",
        ),
        background="#F5FAF0",
        padding="80px 40px",
        width="100%",
        id="ofertas",
        on_mount=OfertasState.cargar_ofertas,
    )

def por_que_elegirnos() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.vstack(
                rx.text(
                    "NUESTRA PROPUESTA",
                    color="#639922",
                    font_size="11px",
                    letter_spacing="3px",
                    font_weight="500",
                ),
                rx.heading(
                    "¿Por qué elegir AventuraRD?",
                    size="7",
                    color="#27500A",
                    text_align="center",
                ),
                spacing="2",
                align="center",
            ),
            rx.grid(
                rx.box(
                    rx.vstack(
                        rx.box(
                            rx.icon("shield", size=24, color="#27500A"),
                            background="#EAF3DE",
                            border_radius="50%",
                            padding="12px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.heading("100% Seguro", size="4", color="#27500A"),
                        rx.text("Guías certificados y equipos de última generación", font_size="13px", color="#666", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px 16px",
                    border="0.5px solid #E8F5E0",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.box(
                            rx.icon("leaf", size=24, color="#27500A"),
                            background="#EAF3DE",
                            border_radius="50%",
                            padding="12px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.heading("Ecoamigable", size="4", color="#27500A"),
                        rx.text("Turismo responsable que cuida la naturaleza dominicana", font_size="13px", color="#666", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px 16px",
                    border="0.5px solid #E8F5E0",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.box(
                            rx.icon("heart", size=24, color="#27500A"),
                            background="#EAF3DE",
                            border_radius="50%",
                            padding="12px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.heading("Experiencia única", size="4", color="#27500A"),
                        rx.text("Aventuras diseñadas para crear memorias increíbles", font_size="13px", color="#666", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px 16px",
                    border="0.5px solid #E8F5E0",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.box(
                            rx.icon("users", size=24, color="#27500A"),
                            background="#EAF3DE",
                            border_radius="50%",
                            padding="12px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.heading("Grupos reducidos", size="4", color="#27500A"),
                        rx.text("Atención personalizada en cada aventura", font_size="13px", color="#666", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px 16px",
                    border="0.5px solid #E8F5E0",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.box(
                            rx.icon("clock", size=24, color="#27500A"),
                            background="#EAF3DE",
                            border_radius="50%",
                            padding="12px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.heading("Flexibilidad", size="4", color="#27500A"),
                        rx.text("Reserva y cancela sin penalización", font_size="13px", color="#666", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px 16px",
                    border="0.5px solid #E8F5E0",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.box(
                            rx.icon("map", size=24, color="#27500A"),
                            background="#EAF3DE",
                            border_radius="50%",
                            padding="12px",
                            display="flex",
                            align_items="center",
                            justify_content="center",
                        ),
                        rx.heading("Destinos únicos", size="4", color="#27500A"),
                        rx.text("Los mejores paisajes de República Dominicana", font_size="13px", color="#666", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px 16px",
                    border="0.5px solid #E8F5E0",
                    text_align="center",
                ),
                columns=rx.breakpoints({"base": "1", "md": "2", "lg": "3"}),
                spacing="5",
                width="100%",
            ),
            spacing="8",
            align="center",
            width="100%",
            max_width="1200px",
            margin="0 auto",
        ),
        background="#F5FAF0",
        padding="80px 40px",
        width="100%",
    )

def stats_section() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.text(
                "NUESTROS NÚMEROS",
                color="#639922",
                font_size="11px",
                letter_spacing="3px",
                font_weight="500",
                text_align="center",
            ),
            rx.grid(
                rx.box(
                    rx.vstack(
                        rx.heading("500+", size="7", color="#27500A", font_weight="500"),
                        rx.box(width="30px", height="2px", background="#639922"),
                        rx.text("Aventureros felices", font_size="12px", color="#639922", font_weight="500", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    border_top="3px solid #639922",
                    padding="20px 12px",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.heading("6", size="7", color="#27500A", font_weight="500"),
                        rx.box(width="30px", height="2px", background="#BA7517"),
                        rx.text("Tipos de aventura", font_size="12px", color="#639922", font_weight="500", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    border_top="3px solid #BA7517",
                    padding="20px 12px",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.heading("10+", size="7", color="#27500A", font_weight="500"),
                        rx.box(width="30px", height="2px", background="#1D9E75"),
                        rx.text("Destinos en RD", font_size="12px", color="#639922", font_weight="500", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="white",
                    border_radius="12px",
                    border_top="3px solid #1D9E75",
                    padding="20px 12px",
                    text_align="center",
                ),
                rx.box(
                    rx.vstack(
                        rx.heading("5★", size="7", color="white", font_weight="500"),
                        rx.box(width="30px", height="2px", background="#FAC775"),
                        rx.text("Calificación promedio", font_size="12px", color="#FAEEDA", font_weight="500", text_align="center"),
                        spacing="3",
                        align="center",
                    ),
                    background="#BA7517",
                    border_radius="12px",
                    border_top="3px solid #FAC775",
                    padding="20px 12px",
                    text_align="center",
                ),
                columns=rx.breakpoints({"base": "2", "md": "4"}),
                spacing="4",
                width="100%",
            ),
            spacing="6",
            align="center",
            width="100%",
            max_width="1200px",
            margin="0 auto",
        ),
        background="#173404",
        padding="50px 40px",
        width="100%",
    )

def testimonios_section() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.vstack(
                rx.text(
                    "LO QUE DICEN NUESTROS CLIENTES",
                    color="#639922",
                    font_size="11px",
                    letter_spacing="3px",
                    font_weight="500",
                ),
                rx.heading(
                    "Aventureros que nos recomiendan",
                    size="7",
                    color="white",
                    text_align="center",
                ),
                spacing="2",
                align="center",
            ),
            rx.grid(
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            spacing="1",
                        ),
                        rx.text(
                            '"El trekking al Pico Duarte fue la experiencia más increíble de mi vida. ¡Los guías son excelentes!"',
                            font_size="14px",
                            color="#444",
                            line_height="1.7",
                            font_style="italic",
                        ),
                        rx.hstack(
                            rx.box(
                                rx.text("MR", font_size="12px", font_weight="500", color="#27500A"),
                                background="#EAF3DE",
                                border_radius="50%",
                                width="36px",
                                height="36px",
                                display="flex",
                                align_items="center",
                                justify_content="center",
                            ),
                            rx.vstack(
                                rx.text("María R.", font_size="13px", font_weight="500", color="#27500A"),
                                rx.text("Santo Domingo", font_size="11px", color="#888"),
                                spacing="0",
                                align="start",
                            ),
                            spacing="3",
                            align="center",
                        ),
                        spacing="4",
                        align="start",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px",
                    border="0.5px solid #E8F5E0",
                ),
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            spacing="1",
                        ),
                        rx.text(
                            '"El rafting en el Yaque fue pura adrenalina. Volveré con toda mi familia el próximo año."',
                            font_size="14px",
                            color="#444",
                            line_height="1.7",
                            font_style="italic",
                        ),
                        rx.hstack(
                            rx.box(
                                rx.text("JG", font_size="12px", font_weight="500", color="#0F6E56"),
                                background="#E1F5EE",
                                border_radius="50%",
                                width="36px",
                                height="36px",
                                display="flex",
                                align_items="center",
                                justify_content="center",
                            ),
                            rx.vstack(
                                rx.text("José G.", font_size="13px", font_weight="500", color="#27500A"),
                                rx.text("Santiago", font_size="11px", color="#888"),
                                spacing="0",
                                align="start",
                            ),
                            spacing="3",
                            align="center",
                        ),
                        spacing="4",
                        align="start",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px",
                    border="0.5px solid #E8F5E0",
                ),
                rx.box(
                    rx.vstack(
                        rx.hstack(
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            rx.icon("star", size=14, color="#FAC775"),
                            spacing="1",
                        ),
                        rx.text(
                            '"El zipline de Jarabacoa fue impresionante. La organización fue perfecta de principio a fin."',
                            font_size="14px",
                            color="#444",
                            line_height="1.7",
                            font_style="italic",
                        ),
                        rx.hstack(
                            rx.box(
                                rx.text("AL", font_size="12px", font_weight="500", color="#854F0B"),
                                background="#FAEEDA",
                                border_radius="50%",
                                width="36px",
                                height="36px",
                                display="flex",
                                align_items="center",
                                justify_content="center",
                            ),
                            rx.vstack(
                                rx.text("Ana L.", font_size="13px", font_weight="500", color="#27500A"),
                                rx.text("La Romana", font_size="11px", color="#888"),
                                spacing="0",
                                align="start",
                            ),
                            spacing="3",
                            align="center",
                        ),
                        spacing="4",
                        align="start",
                    ),
                    background="white",
                    border_radius="12px",
                    padding="24px",
                    border="0.5px solid #E8F5E0",
                ),
                columns=rx.breakpoints({"base": "1", "md": "3"}),
                spacing="5",
                width="100%",
            ),
            spacing="8",
            align="center",
            width="100%",
            max_width="1200px",
            margin="0 auto",
        ),
        background="#27500A",
        padding="80px 40px",
        width="100%",
    )

def cta_section() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.heading(
                "¿Listo para tu próxima aventura?",
                size="7",
                color="white",
                text_align="center",
            ),
            rx.text(
                "Reserva hoy y vive una experiencia que nunca olvidarás",
                color="#9FCC6B",
                font_size="16px",
                text_align="center",
            ),
            rx.hstack(
                rx.link(
                    rx.button(
                        "Ver aventuras",
                        background="#BA7517",
                        color="white",
                        border_radius="8px",
                        padding="14px 32px",
                        font_size="16px",
                        font_weight="600",
                        _hover={"background": "#9A6010"},
                    ),
                    href="#ofertas",
                ),
                rx.link(
                    rx.button(
                        "Contáctanos",
                        background="transparent",
                        color="white",
                        border="2px solid rgba(255,255,255,0.4)",
                        border_radius="8px",
                        padding="14px 32px",
                        font_size="16px",
                        font_weight="600",
                        _hover={"background": "rgba(255,255,255,0.1)"},
                    ),
                    href="#contacto",
                ),
                spacing="4",
                flex_wrap="wrap",
                justify="center",
            ),
            spacing="5",
            align="center",
        ),
        background="linear-gradient(135deg, #173404 0%, #0F6E56 100%)",
        padding="80px 40px",
        width="100%",
    )

def inicio_page() -> rx.Component:
    return rx.vstack(
        navbar(),
        hero_section(),
        search_section(),
        rx.box(height="60px"),
        ofertas_section(),
        por_que_elegirnos(),
        stats_section(),
        testimonios_section(),
        cta_section(),
        footer(),
        spacing="0",
        width="100%",
        on_mount=OfertasState.cargar_categorias,
    )